sources:
  - name: Microsoft Graph
    handler:
      odata:
        baseUrl: https://graph.microsoft.com/${GRAPH_VERSION}
        batch: json
        operationHeaders:
          Authorization: Bearer {context.accessToken}
